

var t1 = ["Business", "Anthroplogical", "Game", "Neoclassical", "Urban", "Radical", "Postmodernist", "Existential", "Posthumanist", "Quantum", "Economic", "360-Degree", "Bayesian", "Holistic", "Socio-cultural", "Philosophical", "Transcendental", "Environmental", "Postcolonial", "Poststructuralist", "Global", "Local", "Transnational", "Rural", "Sustainable", "International", "Nationalist", "Smart", "Regional", "Problematic", "Intersectional", "Artificial", "Complex", "Systemic", "Innovative", "Strategic", "Institutional", "Comparative", "Humanitarian", "Speculative", "Domestic", "Cloud-based", "Monolithic", "Transparent", "Market", "Historical", "Virtual", "Philanthropic", "Semantic", "Experimental", "Heuristic", "Instrumental", "Multidimensional", "Renewable", "Evidence-based", "Pro-active", "Metaphysical", "Populist", "Bottom-up", "Grass-roots", "Civil", "Linguistic", "Theological", "Rhetorical", "Cartesian", "Sophoclean", "Platonic", "Foucauldian", "Gramscian", "Inductive", "Deductive", "Paradigmatic", "Kantian", "Aristotlean", "Objective", "Subjective", "Pseudo-scientific", "Affective", "Post-traumatic", "Pre-modern"]
var t2 = ["Psychology", "Theory", "Research", "Economics", "Futures", "Radicalism", "Libertarianism", "Data Science", "Finance", "Feminism", "Geography", "Management", "Phenomenology", "Neoliberalism", "Algorithms", "Ethics", "Discourse", "Entrepreneurship", "Determinism", "Policy", "Governance", "Decision Science", "Organisational Science", "Methodology", "Epistemology", "Development", "Ecology", "Politics", "Conservatism", "Security", "Precarity", "Planning", "Sociology", "History", "Cities", "Urbanism", "Housing", "Risk Analysis", "Militarism", "Technology", "Philosophy", "Architecture", "Design", "Systems", "Imaginaries", "Fundamentalism", "Philanthropy", "Education", "Systems Design", "Hegemony", "Power Structures", "Research Design", "Funding", "Existentialism", "Paternalism", "Morality", "Rationality", "Pragmatism", "Learning", "Empiricism", "Positivism", "Polymorphism"]
var t3 = ["Social Media", "Russia", "China", "the USA", "the UK", "the EU", "France", "Germany", "Belgium", "Sweden", "Ghana", "Australia", "Ebay", "Amazon", "Apple", "Google", "Facebook", "Mumble Rap", "Cryptocurrency", "Vaping", "Golf Clubs", "Netflix", "Bognor Regis", "Microsoft Office", "Finsbury Park", "Machine Learning", "NASA", "5G", "Geoguessr", "Fox-hunting", "Healthcare", "Hedge Funds", "Climate Change", "Forest Fires", "Public Opinion", "Human Rights", "Societal Transitions", "Culture", "Social Movements", "Social Networks", "Race", "Impact", "Singapore", "Bulgaria", "Football Coaches", "Fried Chicken Shops", "Golf Caddies", "Red Bull", "Snapchat", "OnlyFans", "PDFs", "Rick Astley", "the Vengaboys", "Neural Networks", "Alf from Home and Away", "Justice", "Inequality", "Shrek", "the Workplace", "Virtual Reality", "Buckingham Palace", "Privacy", "Alcoholism", "Drug Dependency", "Mental Wellbeing", "Satanism", "Steroids", "Peppa Pig", "K-Pop", "4Chan", "Twitter", "Municipal Electoral Systems", "Halloween", "Lifelong Learning", "Conspiracy Theories", "Taylor Swift", "Public Transport", "Fiscal Policy", "Recycling", "Waste Management"]
var t4 = ["a critique of the", "an analysis of the", "re-imagining the", "revisiting the", "an examination of the", "exploring the", "unpacking the", "unravelling the mysteries of", "a retrospective of", "a deep dive into", "a rich description of the", "investigations into the", "a metaphorical content analysis of", "a critical discourse analysis of the", "seeking to explain the", "a random effects regression model of", "a time series analysis of", "an evidence-based evaluation of", "a network analysis of", "a novel predictive model of", "a sympathetic reading of the", "an enquiry into the", "understanding the practices of", "learning from the lived experiences of", "confronting the more controversial aspects of", "a convolution neural network model to explore", "a reinforcement learning model to help explain", "the value of applying K-Means clustering to observations of", "combatting the dominant narratives around", "an image-detection system to classify", "questioning accepted assumptions regarding"]
var t5 = ["textile", "poultry", "badminton", "cat-treat", "mars bar", "gerbil", "fried chicken", "petty crime", "custard tart", "gambling", "kitten", "puppy", "ice cream", "money-laundering", "trampoline", "cod liver oil", "chicken nugget", "palm oil", "mouse pad", "whiskey", "pot noodle", "transport", "machine learning", "flamethrower", "ride-sharing", "pesto", "toilet paper", "solar", "dark web", "celebrity", "smart watch", "table tennis", "Bitcoin", "crowd-funding", "frog-breeding", "Big Pharma", "Big Soy", "Big Caffeine", "virtual reality", "pig-breeding", "hamster-farming", "mayonnaise", "steroid", "video game", "racecar", "small business", "fintech", "faith", "ultimate frisbee", "alcoholism", "anorexia", "Nutella", "tourism", "mechanical keyboard", "methamphetamine", "insurance", "healthcare", "smart city", "smart home"]
var t6 = ["industries", "sectors", "neighbourhoods", "cityscapes", "economies", "networks", "spheres", "oligarchy", "policy networks", "elites", "subcultures", "CEOs", "experts", "hackers", "speculators", "policies", "families", "support groups", "communities", "gurus", "farmers", "engineers", "cult leaders", "lobbyists", "groups", "gangs", "regulators", "investigators", "evangelists", "hustlers", "enthusiasts"]
var t7 = ["the 21st century", "the coming years", "the 19th century", "the Cold War period", "the information age", "the era of globalisation", "the 4th industrial revolution", "2021", "the 1990s", "modern cinema", "news media", "popular culture", "the surveillance age", "sub-Saharan Africa", "western Europe", "the Middle East", "South-East Asia", "the Mediterranean", "the Balkans", "the Scottish Highlands", "the upper atmosphere", "one forgotten Cambodian village", "one exquisite rural neighbourhood in Santiago", "one forgotten mining town in Chelyabinsk", "contemporary science fiction literature", "Las Vegas", "one delightful little downtown Havana cafe", "Buckingham Palace", "10 Downing Street", "Notting Hill", "East London council estates", "virtual office spaces", "northern Vienna", "Hamburg's red light district", "the swamps of Louisiana", "corporate culture", "the Moskva River", "the Amazon rainforest", "ancient Egyptian scriptures", "Shakespeare's The Tempest", "Postwar era movie soundtracks", "the lowlands of Borneo", "Papua's emerging paramilitaries", "the lyrical subtexts of Vengaboys chart singles", "cryptocurrency portfolios", "Stalin's diaries", "Prague's thriving baking communities", "Stockholm's flourishing youth centres", "Birmingham's struggling high streets", "Lima's forgotten basketball courts", "ancient Burmese poems", "the former Yugoslavia", "Ghana's thriving streetfood market", "the subtexts of Neil DeGrasse Tyson's tweets", "the American prison system", "the American healthcare system", "Australia's coral reefs", "the thriving swamps of Madagascar", "the post COVID era", "emerging Samoan microcities", "the Google Play store", "the Itunes store", "Apple's marketing philosophy"]

function newPaper() {
	var random1 = Math.floor(Math.random() * (t1.length));
	var random2 = Math.floor(Math.random() * (t2.length));
	var random3 = Math.floor(Math.random() * (t3.length));
	var random4 = Math.floor(Math.random() * (t4.length));
	var random5 = Math.floor(Math.random() * (t5.length));
	var random6 = Math.floor(Math.random() * (t6.length));
	var random7 = Math.floor(Math.random() * (t7.length));
	document.getElementById('paperDisplay').innerHTML = t1[random1] + " " + t2[random2] + " and " + t3[random3] + "; " + t4[random4] + " " + t5[random5] + " " + t6[random6] + " in " + t7[random7];
}
